name: calledworkflow

# Controls when the workflow will run
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: テキストファイルの生成
        run: echo Hello, world!　> test.txt

      - uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: test.txt
