name: called-dowload-workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      push-java:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.10.2  # 好きなバージョンを指定


      - name: Build and Test
        run: gradle clean build
        
      - run: ls -R

      - uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/libs/
  push:
    runs-on: ubuntu-latest
    needs: build
    if: inputs.push-java == true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-files
      - run: ls -R
      - run: echo "Push Modules Done!"
      
  wait_staging:
    runs-on: ubuntu-latest
    needs: push
    timeout-minutes: 1
    continue-on-error: true
    environment: staging   # staging 環境で承認待ち
    steps:
      - run: echo "Waiting for staging approval"

  wait_production:
    runs-on: ubuntu-latest
    needs: push
    timeout-minutes: 1
    continue-on-error: true
    environment: production  # production 環境で承認待ち
    steps:
      - run: echo "Waiting for production approval"

  deploy_staging:
    runs-on: ubuntu-latest
    needs: wait_staging
    steps:
      - run: echo "Deploying to staging"

  deploy_production:
    runs-on: ubuntu-latest
    needs: wait_production  # 両方の承認待ちを待つ
    steps:
      - run: echo "Deploying to production"
      
